language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
script: "bundle exec rake coverage"
gemfile:
  - gemfiles/travis.gemfile
notifications:
  email:
    - support@travellink.com.au
  flowdock: e69dcafad1fea15c6b8c76e9ced965af
